### ISSUE TITLE
When placing on hopper causes server crash

### ISSUE THREAD

**Issue by ftog-thorgal** [gigaherz/Enderthing#14]
Version used: enderthing-1.10.2-0.6.10

Every time I place an Enderthing Ender Chest on a hopper it crashes with the following error:

`java.lang.NullPointerException: Ticking block entity
    at net.minecraftforge.items.VanillaInventoryCodeHooks.extractHook(VanillaInventoryCodeHooks.java:45)
    at net.minecraft.tileentity.TileEntityHopper.func_145891_a(TileEntityHopper.java:361)
    at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:207)
    at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:187)
    at net.minecraft.world.World.func_72939_s(World.java:1802)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)`

**Comment by ftog-thorgal** [comment]
Server doesn't come up anymore and requires MCEdit removal of the placed chest.

**Comment by gigaherz** [comment]
I'll take a look, but I may need some more info: Forge version? Other mods? Any CoreMods active?

**Comment by gigaherz** [comment]
I can't reproduce locally, please provide more info.

The rest of the exception, with the "caused by", would be appreciated.

**Comment by ftog-thorgal** [comment]
Here is the entire crash report: http://pastebin.com/EckY7yVu

**Comment by ftog-thorgal** [comment]
If you need to see what I did you can watch it in my latest video, it might help you seeing what exactly I did. https://www.youtube.com/watch?v=oJl_KUddD88 It's right at the start of the video.

**Comment by gigaherz** [comment]
Oh I see! You forgot to mention is was a PRIVATE inventory, and I completely forgot to test that! I'll report back with either a fix, or more questions.

**Comment by gigaherz** [comment]
Fix is up: https://github.com/gigaherz/Enderthing/releases/tag/v0.6.11-1.10.2
Curseforge incoming.

**Comment by gigaherz** [comment]
Curseforge up too: https://minecraft.curseforge.com/projects/enderthing/files
